config/routes.rb
HerokuPinger::Application.routes.draw do
  # resources :websites
  get '/websites' => 'websites#index', :as => 'websites'
  post '/websites' => 'websites#create'
  get '/websites/new' => 'websites#new', :as => 'new_website'
  get '/websites/:id/edit' => 'websites#edit', :as => 'edit_website'
  get '/websites/:id' => 'websites#show', :as => 'website'
  put '/websites/:id' => 'websites#update'
  delete '/websites/:id' => 'websites#destroy'

  root :to => "home#index"
  resources :users, :only => [ :show, :edit, :update ]
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'
end

app/models/website.rb
  require 'net/http'
  require 'uri'
class Website < ActiveRecord::Base



  VALID_VALUES = [0, 1, 2, 3, 4, 5]

  attr_accessible :failed_tries, :minute, :name, :successful_tries, :summary, :url, :user_id, :good_site

  before_validation :set_minute 
  validates :minute, :inclusion => { :in => VALID_VALUES,
    :message => "%{value} is not a valid value, must be one of 0, 1, 2, 3, 4 or 5" }, :presence => true
  
  validates :user_id, :presence => true
  validates :url, :presence => true
  validates :good_site, :presence => true
  validates :name, :presence => true
  validates_format_of :url, :with => /^(http):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix

  belongs_to :user



  def self.ping_sites
    n = Time.new
    puts "Here is time: #{n}"
    c = Time.new
    time_s = c.to_s
    minute = time_s[14].to_i
    puts "about to call Websites.find_all_blah with minute == #{minute}"

    websites = Website.where("minute = ? AND good_site = ?", minute, true)
    puts "websites.size: #{websites.size}"
    websites.each do |site|
      if Rails.env.development? || Rails.end.test?
        puts "-----"
        puts "Here is the site name: #{site.name}, site url: #{site.url} site minute: #{site.minute} user id: #{site.user_id}"
      end
      result = do_ping(site.url)
      
      # puts result
      if Rails.env.development?
        puts "result.class: #{result.class}"
        puts "result.length: #{result.length}"  
      end
      if result.length == 0
        site.failed_tries += 1
      else
        site.successful_tries += 1
      end
      if site.failed_tries == 5
        site.good_site = false
      end
      site.save
    end

  end

  def self.do_ping(site_url)
    puts "calling do_ping with url #{site_url}"
    uri = URI(site_url)
    Net::HTTP.get(uri)
  end


protected
  def set_minute
    if self.minute.nil?
      self.minute = VALID_VALUES.sample
    end
  end


end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController

  before_filter :signed_in_user, only: [:new, :create, :update, :destroy]
  before_filter :can_user_add_site?, only: :create

  # GET /websites
  # GET /websites.json
  def index
    @websites = Website.order("name ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @websites }
    end
  end

  # GET /websites/1
  # GET /websites/1.json
  def show
    @website = Website.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @website }
    end
  end

  # GET /websites/new
  # GET /websites/new.json
  def new
    @website = Website.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @website }
    end
  end

  # GET /websites/1/edit
  def edit
    @website = Website.find(params[:id])
  end

  # POST /websites
  # POST /websites.json
  def create

    url = params[:website][:url]
    name = params[:website][:name]
    summary = params[:website][:summary]
    # puts "---- current_user: #{current_user}"
    # puts "current_user.id in controller: #{current_user.id}"
    # logger.info session.inspect
    # puts "----------------"
    # puts "#{session.inspect}"
    # puts "----------------"
    user_id = current_user.id
    
    @website = Website.new
    @website.url = url
    @website.name = name
    @website.summary = summary
    @website.user_id = current_user.id
    @website.failed_tries = 0
    @website.successful_tries = 0
    @website.good_site = true

    respond_to do |format|
      if current_user.number_of_sites < 5 &&  @website.save
        current_user.number_of_sites += 1
        current_user.save
        # puts "user.number_of_sites in controller: #{current_user.number_of_sites}"
        # puts "user.id in controller: #{current_user.id}"
        # puts "user.name in controller: #{current_user.name}"
        format.html { redirect_to @website, notice: 'Website was successfully created.' }
        format.json { render json: @website, status: :created, location: @website }
      else
        format.html { render action: "new" }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /websites/1
  # PUT /websites/1.json
  def update
    @website = Website.find(params[:id])

    respond_to do |format|
      if @website.update_attributes(params[:website])
        format.html { redirect_to @website, notice: 'Website was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /websites/1
  # DELETE /websites/1.json
  def destroy
    @website = Website.find(params[:id])
    user_id = current_user.id
    # puts "trying to delete: @website.user_id: #{@website.user_id} current_user.id: #{current_user.id}"
    respond_to do |format|
      if @website.user_id != current_user.id
        # puts "trying to delete with wrong id: @website.user_id: #{@website.user_id} current_user.id: #{current_user.id}"
        format.html { redirect_to websites_url , notice: 'Website entry owned by different user.' }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      elsif @website.destroy
        
        current_user.number_of_sites -= 1
        current_user.save
        format.html { redirect_to websites_url , notice: 'Website was successfully deleted.' }
        format.json { head :no_content }
      end
    end
  end

private 
  def signed_in_user
    redirect_to root_path unless user_signed_in? 
  end

    

end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/websites/_form.html.erb
<%= form_for(@website) do |f| %>
  <% if @website.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@website.errors.count, "error") %> prohibited this website from being saved:</h2>

      <ul>
      <% @website.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
<!--
  <div class="field">
    <%= f.label :minute %><br />
    <%= f.number_field :minute %>
  </div>
-->
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_area :summary %>
  </div>
<!--
  <div class="field">
    <%= f.label :failed_tries %><br />
    <%= f.number_field :failed_tries %>
  </div>
  <div class="field">
    <%= f.label :successful_tries %><br />
    <%= f.number_field :successful_tries %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
-->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/websites/edit.html.erb
<h1>Editing website</h1>

<%= render 'form' %>

<%= link_to 'Show', @website %> |
<%= link_to 'Back', websites_path %>

app/views/websites/index.html.erb
<h1>Listing websites</h1>

<table>
  <tr>
    <th>Url</th>
    <th>Minute</th>
    <th>Name</th>
    <th>Summary</th>
    <th>Failed tries</th>
    <th>Successful tries</th>
    <th>User</th>
    <% if user_signed_in? %>
    <th></th>
    <th></th>
    <th></th>
    <% end %>
  </tr>

<% @websites.each do |website| %>
  <tr>
    <td><%= website.url %></td>
    <td><%= website.minute %></td>
    <td><%= website.name %></td>
    <td><%= website.summary %></td>
    <td><%= website.failed_tries %></td>
    <td><%= website.successful_tries %></td>
    <td><%= website.user.name %></td>
    <% if user_signed_in? %>
    <td><%= link_to 'Show', website %></td>
    <td><%= link_to 'Edit', edit_website_path(website) %></td>
    <td><%= link_to 'Destroy', website, confirm: 'Are you sure?', method: :delete %></td>
    <% end %>
  </tr>
<% end %>


</table>

<br />
<% if user_signed_in?  && current_user.number_of_sites <= 4 %>
<!-- % if can_add_sites? % -->
<%= link_to 'New Website', new_website_path %>
<% end %>

app/views/websites/new.html.erb
<h1>New website</h1>

<%= render 'form' %>

<%= link_to 'Back', websites_path %>

app/views/websites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @website.url %>
</p>

<p>
  <b>Minute:</b>
  <%= @website.minute %>
</p>

<p>
  <b>Name:</b>
  <%= @website.name %>
</p>

<p>
  <b>Summary:</b>
  <%= @website.summary %>
</p>

<p>
  <b>Failed tries:</b>
  <%= @website.failed_tries %>
</p>

<p>
  <b>Successful tries:</b>
  <%= @website.successful_tries %>
</p>

<p>
  <b>User:</b>
  <%= @website.user_id %>
</p>


<%= link_to 'Edit', edit_website_path(@website) %> |
<%= link_to 'Back', websites_path %>